"""Seed a small illustrative cluster with attributed claims."""
import db

con = db.connect()
N = db.add_node
E = db.add_edge
W = "https://en.wikipedia.org/wiki/"          # wikipedia
WD = "https://www.wikidata.org/wiki/"         # wikidata

# --- Hip-hop sampling chain ---
N(con, "work", "Funky Drummer", 1970, "James Brown drum break, most sampled in history")
N(con, "work", "Amen Break", 1969, "The Winstons' break, basis of drum'n'bass/jungle")
N(con, "work", "Planet Rock", 1982, "Afrika Bambaataa & Soulsonic Force")
N(con, "work", "Fight the Power", 1989, "Public Enemy")
N(con, "work", "Straight Outta Compton", 1988, "N.W.A")
N(con, "work", "Rapper's Delight", 1979, "Sugarhill Gang")
N(con, "work", "Good Times", 1979, "Chic")
N(con, "work", "Apache", 1973, "Incredible Bongo Band break")
N(con, "person", "James Brown", 1933, "The Godfather of Soul")
N(con, "person", "Afrika Bambaataa", 1957, "Hip-hop pioneer, Zulu Nation")
N(con, "person", "Chuck D", 1960, "Public Enemy frontman")
N(con, "band", "Chic", 1972, "Disco/funk band")
N(con, "movement", "Hip hop", 1973, "Born in the Bronx")
N(con, "genre", "Drum and bass", 1990)
N(con, "genre", "Breakbeat", 1980)
N(con, "place", "Bronx, New York", None, "Birthplace of hip hop")

E(con, "James Brown", "Funky Drummer", "performed", source_url=W+"Funky_Drummer", source_type="wikipedia", confidence=0.99, verified=1)
E(con, "Planet Rock", "Funky Drummer", "samples", source_url=W+"Planet_Rock_(song)", source_type="wikipedia", confidence=0.95, verified=1)
E(con, "Fight the Power", "Funky Drummer", "samples", source_url=W+"Fight_the_Power_(Public_Enemy_song)", source_type="wikipedia", confidence=0.9, verified=1)
E(con, "Straight Outta Compton", "Funky Drummer", "samples", source_url=W+"Straight_Outta_Compton_(album)", source_type="wikipedia", confidence=0.9, verified=1)
E(con, "Rapper's Delight", "Good Times", "samples", source_url=W+"Rapper%27s_Delight", source_type="wikipedia", confidence=0.99, verified=1)
E(con, "Good Times", "Chic", "performed", source_url=W+"Good_Times_(Chic_song)", source_type="wikipedia", confidence=0.99, verified=1)
E(con, "Planet Rock", "Apache", "samples", source_url=W+"Apache_(Incredible_Bongo_Band_song)", source_type="wikipedia", confidence=0.9, verified=1)
E(con, "Amen Break", "Drum and bass", "founded", source_url=W+"Amen_break", source_type="wikipedia", confidence=0.9, verified=1)
E(con, "Funky Drummer", "Breakbeat", "founded", source_url=W+"Breakbeat", source_type="wikipedia", confidence=0.85, verified=1)
E(con, "Hip hop", "Breakbeat", "uses", source_url=W+"Breakbeat", source_type="wikipedia", confidence=0.8, verified=1)
E(con, "Afrika Bambaataa", "Planet Rock", "performed", source_url=W+"Planet_Rock_(song)", source_type="wikipedia", confidence=0.99, verified=1)
E(con, "Chuck D", "Fight the Power", "performed", source_url=W+"Fight_the_Power_(Public_Enemy_song)", source_type="wikipedia", confidence=0.99, verified=1)
E(con, "Hip hop", "Bronx, New York", "located_in", source_url=W+"Hip_hop_music", source_type="wikipedia", confidence=0.9, verified=1)
E(con, "Afrika Bambaataa", "Hip hop", "member_of", source_url=W+"Afrika_Bambaataa", source_type="wikipedia", confidence=0.9, verified=1)
E(con, "Chuck D", "Hip hop", "member_of", source_url=W+"Chuck_D", source_type="wikipedia", confidence=0.9, verified=1)
E(con, "Fight the Power", "Planet Rock", "references", source_url=W+"Fight_the_Power_(Public_Enemy_song)", source_type="wikipedia", confidence=0.6, verified=0)
E(con, "Straight Outta Compton", "Hip hop", "member_of", source_url=W+"Straight_Outta_Compton_(album)", source_type="wikipedia", confidence=0.9, verified=1)

# --- Visual collage chain ---
N(con, "work", "Cut with the Kitchen Knife Dada", 1919, "Hannah Höch photomontage")
N(con, "work", "Merz", 1923, "Kurt Schwitters collage")
N(con, "work", "Just What Is It...", 1956, "Richard Hamilton pop-art collage")
N(con, "work", "Girl with a Pearl Earring", 1665, "Vermeer")
N(con, "work", "Girl with a Pearl Earring (collage)", 2013, "contemporary collage homage")
N(con, "person", "Hannah Höch", 1889, "Dada photomontage pioneer")
N(con, "person", "Kurt Schwitters", 1887, "Merz artist")
N(con, "person", "Richard Hamilton", 1922, "Pop art founder")
N(con, "person", "Johannes Vermeer", 1632, "Dutch Golden Age painter")
N(con, "movement", "Dada", 1916, "anti-art movement")
N(con, "movement", "Pop art", 1950)
N(con, "concept", "Collage", None, "assembling disparate fragments")
N(con, "concept", "Appropriation", None, "reusing existing imagery")

E(con, "Hannah Höch", "Cut with the Kitchen Knife Dada", "performed", source_url=W+"Hannah_H%C3%B6ch", source_type="wikipedia", confidence=0.99, verified=1)
E(con, "Kurt Schwitters", "Merz", "performed", source_url=W+"Kurt_Schwitters", source_type="wikipedia", confidence=0.99, verified=1)
E(con, "Richard Hamilton", "Just What Is It...", "performed", source_url=W+"Just_what_is_it%3F", source_type="wikipedia", confidence=0.99, verified=1)
E(con, "Johannes Vermeer", "Girl with a Pearl Earring", "performed", source_url=W+"Girl_with_a_Pearl_Earring", source_type="wikipedia", confidence=0.99, verified=1)
E(con, "Cut with the Kitchen Knife Dada", "Collage", "exemplifies", source_url=W+"Cut_with_the_Kitchen_Knife_Dada", source_type="wikipedia", confidence=0.9, verified=1)
E(con, "Merz", "Collage", "exemplifies", source_url=W+"Merz_(art)", source_type="wikipedia", confidence=0.9, verified=1)
E(con, "Just What Is It...", "Collage", "exemplifies", source_url=W+"Just_what_is_it%3F", source_type="wikipedia", confidence=0.9, verified=1)
E(con, "Just What Is It...", "Appropriation", "exemplifies", source_url=W+"Just_what_is_it%3F", source_type="wikipedia", confidence=0.8, verified=1)
E(con, "Girl with a Pearl Earring (collage)", "Girl with a Pearl Earring", "collages", source_url=W+"Girl_with_a_Pearl_Earring", source_type="wikipedia", confidence=0.5, verified=0)
E(con, "Girl with a Pearl Earring (collage)", "Appropriation", "exemplifies", source_url=W+"Appropriation_(art)", source_type="wikipedia", confidence=0.5, verified=0)
E(con, "Hannah Höch", "Dada", "member_of", source_url=W+"Hannah_H%C3%B6ch", source_type="wikipedia", confidence=0.9, verified=1)
E(con, "Kurt Schwitters", "Dada", "member_of", source_url=W+"Kurt_Schwitters", source_type="wikipedia", confidence=0.9, verified=1)
E(con, "Richard Hamilton", "Pop art", "member_of", source_url=W+"Richard_Hamilton_(artist)", source_type="wikipedia", confidence=0.9, verified=1)
E(con, "Pop art", "Dada", "references", source_url=W+"Pop_art", source_type="wikipedia", confidence=0.7, verified=0)
E(con, "Dada", "Collage", "founded", source_url=W+"Dada", source_type="wikipedia", confidence=0.8, verified=1)
E(con, "Pop art", "Appropriation", "uses", source_url=W+"Appropriation_(art)", source_type="wikipedia", confidence=0.8, verified=1)

con.commit()
print("seeded:", db.stats(con))
